name: VanillaCore
version: ${project.version}
main: club.rigox.vanillacore.VanillaCore
api-version: 1.16
authors: [ sebastn_chan ]
website: https://rigox.club
depend:
  - PlaceholderAPI
commands:
  staff:
    description: Command 1.
  freeze:
    description: Command freeze
  unfreeze:
    description: Command unfreze
  fly:
    description: Command fly