name: Coffee
version: ${project.version}
main: club.rigox.coffee.Coffee
api-version: 1.16
authors: [ sebastn_chan ]
website: https://rigox.club
depend:
  - PlaceholderAPI
  - LuckPerms
commands:
  staff:
    description: Command 1.
  freeze:
    description: Command freeze
  invsee:
    description: Command invsee
  playertp:
    description: Command playertp