name: VanillaCore
version: ${project.version}
main: club.rigox.vanillacore.VanillaCore
api-version: 1.16
authors: [ sebastn_chan ]
website: https://rigox.club
depend:
  - PlaceholderAPI
  - LuckPerms
commands:
  staff:
    description: Command 1.
  freeze:
    description: Command freeze
  fly:
    description: Command fly
  invsee:
    description: Command invsee
  god:
    description: Command god
  playertp:
    description: Command playertp
  coffee:
    description: Command help