debug: true

titles:
  freeze:
    title: "&c&lYOU ARE FROZED!"
    subtitle: "&ePlease follow %s instructions in the chat."
    options:
      fadein: 10
      stay: 40
      fadeout: 10
  unfreeze:
    title: "&a&lYOU HAVE BEEN UNFROZED!"
    subtitle: "&eThank you for your time."
    options:
      fadein: 10
      stay: 40
      fadeout: 10

staff-items:
  LIME_DYE:
    name: "&aVanish Enabled &7(Right Click)"
  GRAY_DYE:
    name: "&cVanish Disabled &7(Right Click)"
  ICE:
    name: "&eFreeze &7(Right Click)"
  BOOK:
    name: "&eView Inventory &7(Right Click)"
  FIREWORK_ROCKET:
    name: "&eLaunch &7(Right Click)"
  COMPASS:
    name: "&ePlayer Teleport &7(Right Click)"

teleport-gui:
  title: "&a%player_name%"
  lore:
    - ""
    - "&7Coords"
    - "&7X = &f%player_x%"
    - "&7Y = &f%player_y%"
    - "&7Z = &f%player_z%"
    - ""
    - "&eClick to teleport!"

